/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.campitos.pelicula;

import com.jc.model.Conexion;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.campitos.pelicula//Asientos//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "AsientosTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "org.campitos.pelicula.AsientosTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_AsientosAction",
        preferredID = "AsientosTopComponent"
)
@Messages({
    "CTL_AsientosAction=Asientos",
    "CTL_AsientosTopComponent=Asientos Window",
    "HINT_AsientosTopComponent=This is a Asientos window"
})
public final class AsientosTopComponent extends TopComponent {
  public static int   lugar=0;

  public static JLabel[] asientos=new JLabel[25];
    public AsientosTopComponent() {
        initComponents();
        setName(Bundle.CTL_AsientosTopComponent());
        setToolTipText(Bundle.HINT_AsientosTopComponent());
       
for(JLabel asiento: asientos){
    asiento=new JLabel("a:"+1);
  asiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/campitos/pelicula/asiento.png"))); 
  asiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
  asiento.setName("perro:"+lugar);
  asiento.addMouseListener(new Mousesito());
  
    jPanel1.add(asiento);
  lugar++;
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AsientosTopComponent.class, "AsientosTopComponent.jLabel1.text")); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(5, 5));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/campitos/pelicula/asiento.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AsientosTopComponent.class, "AsientosTopComponent.jLabel2.text")); // NOI18N
        jLabel2.setToolTipText(org.openide.util.NbBundle.getMessage(AsientosTopComponent.class, "AsientosTopComponent.jLabel2.toolTipText")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
class Mousesito implements MouseListener{

    @Override
    public void mouseClicked(MouseEvent e) {
     System.out.println("me haz cliqueado!!!");
     System.out.println(e.getComponent().getName());
     
     //CONEXIONSITA
     try{
       Conexion c=new Conexion();
        Connection con=c.conectarse();
     CallableStatement callate=con.prepareCall("{call guardar_pelicula(?,?,?,?)}");
        callate.registerOutParameter(1,java.sql.Types.INTEGER);
        callate.setString(2,"la muñeca mala");
        callate.setString(3,"almodovar");
         callate.setString(4,"Es de miedo uuuuy");
      
        callate.execute();
        int pk=callate.getInt(1);
        System.out.println("Se guardo con una pk:"+pk);
     }catch(Exception es){
         System.out.println("paso esto:"+es.getMessage());
     }

    }

    @Override
    public void mousePressed(MouseEvent e) {
  
    }

    @Override
    public void mouseReleased(MouseEvent e) {
 // System.out.println("Lo soltaste");
    }

    @Override
    public void mouseEntered(MouseEvent e) {
  //System.out.println("Hasz entrado");
    }

    @Override
    public void mouseExited(MouseEvent e) {
  //System.out.println("te haz salidos");
    }
    
}